spring.application.name=chatserver

spring.datasource.url=jdbc:postgresql://chatserver-postgres:5432/chatserver
spring.datasource.username=dev
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=9!3>/MWy<^)xouo){|]-/AWmm^^SlA7M-<|J7W(id(i
jwt.expiration=86400000