services:
  chatserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatserver
    depends_on:
      - chatserver-postgres
    ports:
      - "8080:8080"
    networks:
      - chatnet

  chatserver-postgres:
    image: postgres:latest
    container_name: postgres-chatserver
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: chatserver
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always
    networks:
      - chatnet

volumes:
  postgres_data:
    driver: local

networks:
  chatnet:
    driver: bridge